# Generated by Django 5.0.4 on 2025-06-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilledguild', '0004_post_image_post_tags_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='organiser_logos/')),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., Club Chapter, Host Institute', max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsor_logos/')),
                ('description', models.TextField()),
                ('type', models.CharField(help_text='e.g., Title Sponsor, Outreach Partner', max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
